Keyword.create(item: "Butter", name: "Grocery")
Keyword.create(item: "Butter, no salt", name: "Grocery")
Keyword.create(item: "Butter, salted", name: "Grocery")
Keyword.create(item: "Cheese", name: "Grocery")
Keyword.create(item: "Cheese slices", name: "Grocery")
Keyword.create(item: "Cheese spread", name: "Grocery")
Keyword.create(item: "Cheese, specialty", name: "Grocery")
Keyword.create(item: "Chip dip", name: "Grocery")
Keyword.create(item: "Cottage cheese", name: "Grocery")
Keyword.create(item: "Cream cheese", name: "Grocery")
Keyword.create(item: "Cream, heavy", name: "Grocery")
Keyword.create(item: "Egg Nog", name: "Grocery")
Keyword.create(item: "Egg substitute", name: "Grocery")
Keyword.create(item: "Eggs", name: "Grocery")
Keyword.create(item: "Fruit juice", name: "Grocery")
Keyword.create(item: "Half & half", name: "Grocery")
Keyword.create(item: "Margarine", name: "Grocery")
Keyword.create(item: "Milk", name: "Grocery")
Keyword.create(item: "Pate", name: "Grocery")
Keyword.create(item: "Ready bake goods", name: "Grocery")
Keyword.create(item: "Sour cream", name: "Grocery")
Keyword.create(item: "Soy milk", name: "Grocery")
Keyword.create(item: "Tofu", name: "Grocery")
Keyword.create(item: "Whipping cream", name: "Grocery")
Keyword.create(item: "Yogurt Bagels", name: "Grocery")
Keyword.create(item: "Baguette", name: "Grocery")
Keyword.create(item: "Brownies", name: "Grocery")
Keyword.create(item: "Buns", name: "Grocery")
Keyword.create(item: "Cake", name: "Grocery")
Keyword.create(item: "Cheese bread", name: "Grocery")
Keyword.create(item: "Cinnamon buns", name: "Grocery")
Keyword.create(item: "Cookies", name: "Grocery")
Keyword.create(item: "Croissants", name: "Grocery")
Keyword.create(item: "Doughnuts", name: "Grocery")
Keyword.create(item: "English muffins", name: "Grocery")
Keyword.create(item: "French bread", name: "Grocery")
Keyword.create(item: "Garlic bread", name: "Grocery")
Keyword.create(item: "Hamburger buns", name: "Grocery")
Keyword.create(item: "Hot dog buns", name: "Grocery")
Keyword.create(item: "Pie", name: "Grocery")
Keyword.create(item: "Pita bread", name: "Grocery")
Keyword.create(item: "Pumpernickel", name: "Grocery")
Keyword.create(item: "Raisin bread Rye bread", name: "Grocery")
Keyword.create(item: "Sandwich bread", name: "Grocery")
Keyword.create(item: "Sourdough", name: "Grocery")
Keyword.create(item: "Tortillas,flour", name: "Grocery")
Keyword.create(item: "Tortillas,corn", name: "Grocery")
Keyword.create(item: "Burritos,flour", name: "Grocery")
Keyword.create(item: "Tortillas,corn", name: "Grocery")
Keyword.create(item: "Whole grain Asparagus", name: "Grocery")
Keyword.create(item: "Avocados", name: "Grocery")
Keyword.create(item: "Basil", name: "Grocery")
Keyword.create(item: "Beets", name: "Grocery")
Keyword.create(item: "Broccoli", name: "Grocery")
Keyword.create(item: "Brussels sprouts", name: "Grocery")
Keyword.create(item: "Cabbage", name: "Grocery")
Keyword.create(item: "Carrots", name: "Grocery")
Keyword.create(item: "Cauliflower", name: "Grocery")
Keyword.create(item: "Celery", name: "Grocery")
Keyword.create(item: "Chard", name: "Grocery")
Keyword.create(item: "Chives", name: "Grocery")
Keyword.create(item: "Cilanto", name: "Grocery")
Keyword.create(item: "Collards", name: "Grocery")
Keyword.create(item: "Corn", name: "Grocery")
Keyword.create(item: "Cucumbers", name: "Grocery")
Keyword.create(item: "Egg plant", name: "Grocery")
Keyword.create(item: "Endives", name: "Grocery")
Keyword.create(item: "Garlic", name: "Grocery")
Keyword.create(item: "Green peppers", name: "Grocery")
Keyword.create(item: "Kale", name: "Grocery")
Keyword.create(item: "Kohlrabi", name: "Grocery")
Keyword.create(item: "Lettuce, iceberg", name: "Grocery")
Keyword.create(item: "Lettuce, romaine", name: "Grocery")
Keyword.create(item: "Mushrooms Onions", name: "Grocery")
Keyword.create(item: "Oregano", name: "Grocery")
Keyword.create(item: "Parsley", name: "Grocery")
Keyword.create(item: "Parsnips", name: "Grocery")
Keyword.create(item: "Potatoes", name: "Grocery")
Keyword.create(item: "Pumpkin", name: "Grocery")
Keyword.create(item: "Radishes", name: "Grocery")
Keyword.create(item: "Red peppers", name: "Grocery")
Keyword.create(item: "Rutabagas", name: "Grocery")
Keyword.create(item: "Spinach", name: "Grocery")
Keyword.create(item: "Sprouts", name: "Grocery")
Keyword.create(item: "Squash", name: "Grocery")
Keyword.create(item: "Tomatoes", name: "Grocery")
Keyword.create(item: "Yams", name: "Grocery")
Keyword.create(item: "Yellow peppers", name: "Grocery")
Keyword.create(item: "Zucchini Apples", name: "Grocery")
Keyword.create(item: "Apricots", name: "Grocery")
Keyword.create(item: "Bananas", name: "Grocery")
Keyword.create(item: "Blueberries", name: "Grocery")
Keyword.create(item: "Cantaloupe", name: "Grocery")
Keyword.create(item: "Cherries", name: "Grocery")
Keyword.create(item: "Cranberries", name: "Grocery")
Keyword.create(item: "Grapes, red", name: "Grocery")
Keyword.create(item: "Grapes, white", name: "Grocery")
Keyword.create(item: "Grapefruit", name: "Grocery")
Keyword.create(item: "Honeydew", name: "Grocery")
Keyword.create(item: "Kiwi", name: "Grocery")
Keyword.create(item: "Kumquats", name: "Grocery")
Keyword.create(item: "Limes", name: "Grocery")
Keyword.create(item: "Lemons", name: "Grocery")
Keyword.create(item: "Mangoes", name: "Grocery")
Keyword.create(item: "Melon", name: "Grocery")
Keyword.create(item: "Nectarines", name: "Grocery")
Keyword.create(item: "Oranges", name: "Grocery")
Keyword.create(item: "Orange Juice", name: "Grocery")
Keyword.create(item: "Apple Juice", name: "Grocery")
Keyword.create(item: "Papaya", name: "Grocery")
Keyword.create(item: "Peaches", name: "Grocery")
Keyword.create(item: "Pears", name: "Grocery")
Keyword.create(item: "Pineapple Plums", name: "Grocery")
Keyword.create(item: "Raspberries", name: "Grocery")
Keyword.create(item: "Strawberries", name: "Grocery")
Keyword.create(item: "Clams", name: "Grocery")
Keyword.create(item: "Cod", name: "Grocery")
Keyword.create(item: "Crab", name: "Grocery")
Keyword.create(item: "Flounder", name: "Grocery")
Keyword.create(item: "Halibut", name: "Grocery")
Keyword.create(item: "Lobster", name: "Grocery")
Keyword.create(item: "Mussels", name: "Grocery")
Keyword.create(item: "Oysters", name: "Grocery")
Keyword.create(item: "Red snapper", name: "Grocery")
Keyword.create(item: "Salmon", name: "Grocery")
Keyword.create(item: "Shrimp Tilapia", name: "Grocery")
Keyword.create(item: "Tuna", name: "Grocery")
Keyword.create(item: "Sword fish Beans, green", name: "Grocery")
Keyword.create(item: "Beef pot pie", name: "Grocery")
Keyword.create(item: "Berries", name: "Grocery")
Keyword.create(item: "Burger patties", name: "Grocery")
Keyword.create(item: "Burritos", name: "Grocery")
Keyword.create(item: "Carrots", name: "Grocery")
Keyword.create(item: "Chicken", name: "Grocery")
Keyword.create(item: "Chicken nuggets", name: "Grocery")
Keyword.create(item: "Chicken pot pie", name: "Grocery")
Keyword.create(item: "Chicken wings", name: "Grocery")
Keyword.create(item: "Corn dogs", name: "Grocery")
Keyword.create(item: "Fish sticks", name: "Grocery")
Keyword.create(item: "French fries", name: "Grocery")
Keyword.create(item: "Fruit", name: "Grocery")
Keyword.create(item: "Hash browns", name: "Grocery")
Keyword.create(item: "Ice cream", name: "Grocery")
Keyword.create(item: "Juice concentrate", name: "Grocery")
Keyword.create(item: "Mozzarella sticks", name: "Grocery")
Keyword.create(item: "Onion rings", name: "Grocery")
Keyword.create(item: "Cereal", name: "Grocery")
Keyword.create(item: "Pancakes", name: "Grocery")
Keyword.create(item: "Pasta, Fresh", name: "Grocery")
Keyword.create(item: "Peas", name: "Grocery")
Keyword.create(item: "Perogies Pie", name: "Grocery")
Keyword.create(item: "Pizza", name: "Grocery")
Keyword.create(item: "Pizza snacks", name: "Grocery")
Keyword.create(item: "Popsicles", name: "Grocery")
Keyword.create(item: "Potato nuggets", name: "Grocery")
Keyword.create(item: "Ready bake treats", name: "Grocery")
Keyword.create(item: "Sorbet", name: "Grocery")
Keyword.create(item: "Stir fry", name: "Grocery")
Keyword.create(item: "Mixed vegetables", name: "Grocery")
Keyword.create(item: "Taquitos", name: "Grocery")
Keyword.create(item: "Tater tots", name: "Grocery")
Keyword.create(item: "Turkey", name: "Grocery")
Keyword.create(item: "Turkey pot pie", name: "Grocery")
Keyword.create(item: "TV dinners", name: "Grocery")
Keyword.create(item: "Veggie burgers", name: "Grocery")
Keyword.create(item: "Waffles Bacon", name: "Grocery")
Keyword.create(item: "Bacon, canadian", name: "Grocery")
Keyword.create(item: "Bologna", name: "Grocery")
Keyword.create(item: "Chicken bologna", name: "Grocery")
Keyword.create(item: "Chicken breast", name: "Grocery")
Keyword.create(item: "Chicken legs", name: "Grocery")
Keyword.create(item: "Chicken loaf", name: "Grocery")
Keyword.create(item: "Chicken, whole", name: "Grocery")
Keyword.create(item: "Corned beef", name: "Grocery")
Keyword.create(item: "Ground beef", name: "Grocery")
Keyword.create(item: "Ground pork", name: "Grocery")
Keyword.create(item: "Ham", name: "Grocery")
Keyword.create(item: "Ham, black forest", name: "Grocery")
Keyword.create(item: "Ham, smoked", name: "Grocery")
Keyword.create(item: "Ham, honey", name: "Grocery")
Keyword.create(item: "Hamburgers", name: "Grocery")
Keyword.create(item: "Hot dogs", name: "Grocery")
Keyword.create(item: "Liver Pizza", name: "Grocery")
Keyword.create(item: "Pork chops", name: "Grocery")
Keyword.create(item: "Roast beef", name: "Grocery")
Keyword.create(item: "Salami", name: "Grocery")
Keyword.create(item: "Sausage", name: "Grocery")
Keyword.create(item: "Pepperoni", name: "Grocery")
Keyword.create(item: "Steak", name: "Grocery")
Keyword.create(item: "Turkey", name: "Grocery")
Keyword.create(item: "Turkey breast", name: "Grocery")
Keyword.create(item: "Veggie dogs", name: "Grocery")
Keyword.create(item: "Veggie burgers Aluminum foil", name: "Grocery")
Keyword.create(item: "Candles", name: "Grocery")
Keyword.create(item: "Facial tissue", name: "Grocery")
Keyword.create(item: "Lunch bags", name: "Grocery")
Keyword.create(item: "Napkins", name: "Grocery")
Keyword.create(item: "Paper plates", name: "Grocery")
Keyword.create(item: "Paper towel", name: "Grocery")
Keyword.create(item: "Plastic containers", name: "Grocery")
Keyword.create(item: "Plastic cups", name: "Grocery")
Keyword.create(item: "Plastic cutlery", name: "Grocery")
Keyword.create(item: "Plastic wrap", name: "Grocery")
Keyword.create(item: "Sandwich bags", name: "Grocery")
Keyword.create(item: "Sealable bags", name: "Grocery")
Keyword.create(item: "Toilet paper", name: "Grocery")
Keyword.create(item: "Wax paper", name: "Grocery")
Keyword.create(item: "Party favors Anchovies", name: "Grocery")
Keyword.create(item: "Apple sauce", name: "Grocery")
Keyword.create(item: "Bean salad", name: "Grocery")
Keyword.create(item: "Beans", name: "Grocery")
Keyword.create(item: "Beans, baked", name: "Grocery")
Keyword.create(item: "Beans, black", name: "Grocery")
Keyword.create(item: "Beans, Fava", name: "Grocery")
Keyword.create(item: "Beans, green fancy", name: "Grocery")
Keyword.create(item: "Beans, green", name: "Grocery")
Keyword.create(item: "Beans, refried", name: "Grocery")
Keyword.create(item: "Beans, Lima", name: "Grocery")
Keyword.create(item: "Pork & beans", name: "Grocery")
Keyword.create(item: "Soup", name: "Grocery")
Keyword.create(item: "Stew", name: "Grocery")
Keyword.create(item: "Chick peas", name: "Grocery")
Keyword.create(item: "Chicken, flaked", name: "Grocery")
Keyword.create(item: "Chili", name: "Grocery")
Keyword.create(item: "Chocolate sauce", name: "Grocery")
Keyword.create(item: "Corn, whole", name: "Grocery")
Keyword.create(item: "Corn, creamed", name: "Grocery")
Keyword.create(item: "Escargot (snails)", name: "Grocery")
Keyword.create(item: "Fruit salad Peaches", name: "Grocery")
Keyword.create(item: "Pears", name: "Grocery")
Keyword.create(item: "Pineapple", name: "Grocery")
Keyword.create(item: "Peas", name: "Grocery")
Keyword.create(item: "Ravioli", name: "Grocery")
Keyword.create(item: "Oysters", name: "Grocery")
Keyword.create(item: "Salmon", name: "Grocery")
Keyword.create(item: "Sardines", name: "Grocery")
Keyword.create(item: "Spam", name: "Grocery")
Keyword.create(item: "Tomatoes", name: "Grocery")
Keyword.create(item: "Tuna", name: "Grocery")
Keyword.create(item: "Tuna, flaked", name: "Grocery")
Keyword.create(item: "Turkey, flaked Broccoli soup", name: "Grocery")
Keyword.create(item: "Bouillon cubes, beef", name: "Grocery")
Keyword.create(item: "Bouillon cubes, chicken", name: "Grocery")
Keyword.create(item: "Chicken noodle soup", name: "Grocery")
Keyword.create(item: "Coffee whitener", name: "Grocery")
Keyword.create(item: "Coffee ground", name: "Grocery")
Keyword.create(item: "Coffee instant", name: "Grocery")
Keyword.create(item: "Coffee", name: "Grocery")
Keyword.create(item: "Cookies", name: "Grocery")
Keyword.create(item: "Couscous", name: "Grocery")
Keyword.create(item: "Crackers", name: "Grocery")
Keyword.create(item: "Drink crystals", name: "Grocery")
Keyword.create(item: "Mashed potatoes", name: "Grocery")
Keyword.create(item: "Instant Noodles", name: "Grocery")
Keyword.create(item: "Linguini", name: "Grocery")
Keyword.create(item: "Mac&cheese", name: "Grocery")
Keyword.create(item: "Macaroni Onion soup", name: "Grocery")
Keyword.create(item: "Potato soup", name: "Grocery")
Keyword.create(item: "Rice", name: "Grocery")
Keyword.create(item: "Rice, brown", name: "Grocery")
Keyword.create(item: "Rice, instant", name: "Grocery")
Keyword.create(item: "Rice, long grain", name: "Grocery")
Keyword.create(item: "Pasta", name: "Grocery")
Keyword.create(item: "Rotini", name: "Grocery")
Keyword.create(item: "Spaghetti", name: "Grocery")
Keyword.create(item: "Tea", name: "Grocery")
Keyword.create(item: "Basil", name: "Grocery")
Keyword.create(item: "Bay leaf", name: "Grocery")
Keyword.create(item: "Cilantro", name: "Grocery")
Keyword.create(item: "Cinnamon", name: "Grocery")
Keyword.create(item: "Cloves", name: "Grocery")
Keyword.create(item: "Garlic", name: "Grocery")
Keyword.create(item: "Ginger", name: "Grocery")
Keyword.create(item: "Meat tenderizer", name: "Grocery")
Keyword.create(item: "Mint", name: "Grocery")
Keyword.create(item: "Montreal meat spice", name: "Grocery")
Keyword.create(item: "Oregano", name: "Grocery")
Keyword.create(item: "Paprika", name: "Grocery")
Keyword.create(item: "Parsley", name: "Grocery")
Keyword.create(item: "Pepper", name: "Grocery")
Keyword.create(item: "Salt Alfredo sauce", name: "Grocery")
Keyword.create(item: "Apple sauce", name: "Grocery")
Keyword.create(item: "Chili Sauce", name: "Grocery")
Keyword.create(item: "BBQ sauce", name: "Grocery")
Keyword.create(item: "Gravy", name: "Grocery")
Keyword.create(item: "Honey", name: "Grocery")
Keyword.create(item: "Hot sauce", name: "Grocery")
Keyword.create(item: "HP sauce", name: "Grocery")
Keyword.create(item: "Jam", name: "Grocery")
Keyword.create(item: "Jelly", name: "Grocery")
Keyword.create(item: "Ketchup", name: "Grocery")
Keyword.create(item: "Marmalade", name: "Grocery")
Keyword.create(item: "Mayonnaise", name: "Grocery")
Keyword.create(item: "Meat sauce", name: "Grocery")
Keyword.create(item: "Mustard", name: "Grocery")
Keyword.create(item: "Nacho dip", name: "Grocery")
Keyword.create(item: "Olives", name: "Grocery")
Keyword.create(item: "Olives, black", name: "Grocery")
Keyword.create(item: "Olives, green", name: "Grocery")
Keyword.create(item: "Pasta sauce Peanut butter", name: "Grocery")
Keyword.create(item: "Pickles", name: "Grocery")
Keyword.create(item: "Relish", name: "Grocery")
Keyword.create(item: "Salad dressing", name: "Grocery")
Keyword.create(item: "Salsa", name: "Grocery")
Keyword.create(item: "Soy sauce", name: "Grocery")
Keyword.create(item: "Steak sauce", name: "Grocery")
Keyword.create(item: "Sweet & sour sauce", name: "Grocery")
Keyword.create(item: "Syrup", name: "Grocery")
Keyword.create(item: "Tartar Sauce", name: "Grocery")
Keyword.create(item: "Tomato paste", name: "Grocery")
Keyword.create(item: "Tomato sauce", name: "Grocery")
Keyword.create(item: "Worcestershire sauce Breath mints", name: "Grocery")
Keyword.create(item: "Candy", name: "Grocery")
Keyword.create(item: "Cheezies", name: "Grocery")
Keyword.create(item: "Chips", name: "Grocery")
Keyword.create(item: "Chocolate", name: "Grocery")
Keyword.create(item: "Club soda", name: "Grocery")
Keyword.create(item: "Corn chips", name: "Grocery")
Keyword.create(item: "Dried fruit", name: "Grocery")
Keyword.create(item: "Granola bars", name: "Grocery")
Keyword.create(item: "Gum", name: "Grocery")
Keyword.create(item: "Hickory sticks", name: "Grocery")
Keyword.create(item: "Juice", name: "Grocery")
Keyword.create(item: "Mineral water", name: "Grocery")
Keyword.create(item: "Mixers", name: "Grocery")
Keyword.create(item: "Nacho chips Nuts, mixed", name: "Grocery")
Keyword.create(item: "Peanuts", name: "Grocery")
Keyword.create(item: "Pop", name: "Grocery")
Keyword.create(item: "Popcorn", name: "Grocery")
Keyword.create(item: "Pork rinds", name: "Grocery")
Keyword.create(item: "Pretzels", name: "Grocery")
Keyword.create(item: "Protein bars", name: "Grocery")
Keyword.create(item: "Sport drink", name: "Grocery")
Keyword.create(item: "Trail mix Baking powder", name: "Grocery")
Keyword.create(item: "Baking soda", name: "Grocery")
Keyword.create(item: "Bisquick", name: "Grocery")
Keyword.create(item: "Bread crumbs", name: "Grocery")
Keyword.create(item: "Brownie mix", name: "Grocery")
Keyword.create(item: "Brown sugar", name: "Grocery")
Keyword.create(item: "Cake mix", name: "Grocery")
Keyword.create(item: "Cocoa powder", name: "Grocery")
Keyword.create(item: "Corn meal", name: "Grocery")
Keyword.create(item: "Decorations", name: "Grocery")
Keyword.create(item: "Flour, white", name: "Grocery")
Keyword.create(item: "Flour, whole wheat", name: "Grocery")
Keyword.create(item: "Graham crumbles", name: "Grocery")
Keyword.create(item: "Icing sugar", name: "Grocery")
Keyword.create(item: "Icing", name: "Grocery")
Keyword.create(item: "Lemon juice", name: "Grocery")
Keyword.create(item: "Jell-O", name: "Grocery")
Keyword.create(item: "Maple syrup", name: "Grocery")
Keyword.create(item: "Non-stick spray", name: "Grocery")
Keyword.create(item: "Nuts", name: "Grocery")
Keyword.create(item: "Molasses", name: "Grocery")
Keyword.create(item: "Muffin Mix", name: "Grocery")
Keyword.create(item: "Oatmeal, instant", name: "Grocery")
Keyword.create(item: "Oatmeal, regular", name: "Grocery")
Keyword.create(item: "Olive Oil", name: "Grocery")
Keyword.create(item: "Pancake mix", name: "Grocery")
Keyword.create(item: "Peanuts", name: "Grocery")
Keyword.create(item: "Pectin", name: "Grocery")
Keyword.create(item: "Salt", name: "Grocery")
Keyword.create(item: "Shortening", name: "Grocery")
Keyword.create(item: "Sprinkles", name: "Grocery")
Keyword.create(item: "Sugar", name: "Grocery")
Keyword.create(item: "Sugar substitute", name: "Grocery")
Keyword.create(item: "Vanilla extract", name: "Grocery")
Keyword.create(item: "Vinegar, white", name: "Grocery")
Keyword.create(item: "Vinegar, balsamic", name: "Grocery")
Keyword.create(item: "Yeast", name: "Grocery")
Keyword.create(item: "Baby wipes", name: "Grocery")
Keyword.create(item: "Diapers", name: "Grocery")
Keyword.create(item: "Baby food", name: "Grocery")
Keyword.create(item: "Formula", name: "Grocery")
Keyword.create(item: "Baby Lotion", name: "Grocery")
Keyword.create(item: "Diaper rash ointment", name: "Grocery")
Keyword.create(item: "Baby shampoo", name: "Grocery")
Keyword.create(item: "Baby wash", name: "Grocery")
Keyword.create(item: "Pabulum", name: "Grocery")
Keyword.create(item: "Baby cookies", name: "Grocery")
Keyword.create(item: "Bottle liners", name: "Grocery")
Keyword.create(item: "Bottle nipples Bottles", name: "Grocery")
Keyword.create(item: "Teething ring", name: "Grocery")
Keyword.create(item: "Teething ointment", name: "Grocery")
Keyword.create(item: "Breast pads", name: "Grocery")
Keyword.create(item: "Bran", name: "Grocery")
Keyword.create(item: "Corn flakes", name: "Grocery")
Keyword.create(item: "Cream of wheat", name: "Grocery")
Keyword.create(item: "Granola Bars", name: "Grocery")
Keyword.create(item: "Grape nuts", name: "Grocery")
Keyword.create(item: "Honey comb", name: "Grocery")
Keyword.create(item: "Honey nut ohs", name: "Grocery")
Keyword.create(item: "Kid's cereal", name: "Grocery")
Keyword.create(item: "Life", name: "Grocery")
Keyword.create(item: "Mini wheats", name: "Grocery")
Keyword.create(item: "Muslix", name: "Grocery")
Keyword.create(item: "Oat meal", name: "Grocery")
Keyword.create(item: "Oatmeal", name: "Grocery")
Keyword.create(item: "Puffed wheat Raisin bran", name: "Grocery")
Keyword.create(item: "Rice crispies", name: "Grocery")
Keyword.create(item: "Shreddies", name: "Grocery")
Keyword.create(item: "Vector", name: "Grocery")
Keyword.create(item: "Air freshener", name: "Grocery")
Keyword.create(item: "Bathroom cleaner", name: "Grocery")
Keyword.create(item: "Bleach", name: "Grocery")
Keyword.create(item: "Carpet cleaner", name: "Grocery")
Keyword.create(item: "Carpet freshener", name: "Grocery")
Keyword.create(item: "Dish soap", name: "Grocery")
Keyword.create(item: "Dishwasher detergent", name: "Grocery")
Keyword.create(item: "Fabric softener", name: "Grocery")
Keyword.create(item: "Garbage bags", name: "Grocery")
Keyword.create(item: "Glass's cleaner", name: "Grocery")
Keyword.create(item: "Kitchen cleaner", name: "Grocery")
Keyword.create(item: "Laundry detergent", name: "Grocery")
Keyword.create(item: "Oven cleaner", name: "Grocery")
Keyword.create(item: "Paper towels Pot scrubbers", name: "Grocery")
Keyword.create(item: "Scrubbers", name: "Grocery")
Keyword.create(item: "Sponges", name: "Grocery")
Keyword.create(item: "Toilet bowl cleaner", name: "Grocery")
Keyword.create(item: "Toilet tank fresheners", name: "Grocery")
Keyword.create(item: "Tub&Tile cleaner", name: "Grocery")
Keyword.create(item: "Vacuum bags", name: "Grocery")
Keyword.create(item: "Cat food, dry", name: "Grocery")
Keyword.create(item: "Cat food, wet", name: "Grocery")
Keyword.create(item: "Cat litter", name: "Grocery")
Keyword.create(item: "Dental/Breath bones", name: "Grocery")
Keyword.create(item: "Dog food, dry", name: "Grocery")
Keyword.create(item: "Dog food, wet", name: "Grocery")
Keyword.create(item: "Flea collar", name: "Grocery")
Keyword.create(item: "Shampoo", name: "Grocery")
Keyword.create(item: "Treats", name: "Grocery")
Keyword.create(item: "Toys", name: "Grocery")
Keyword.create(item: "Reflective collar", name: "Grocery")
Keyword.create(item: "Medicine Grooming comb", name: "Grocery")
Keyword.create(item: "Nail clippers", name: "Grocery")
Keyword.create(item: "Catnip", name: "Grocery")
Keyword.create(item: "Chew toy", name: "Grocery")
Keyword.create(item: "Allergy medication", name: "Grocery")
Keyword.create(item: "Antacids", name: "Grocery")
Keyword.create(item: "Antiseptic - Rubbing alcohol", name: "Grocery")
Keyword.create(item: "Antiseptic - Hydrogen Peroxide", name: "Grocery")
Keyword.create(item: "Antibiotic Ointment", name: "Grocery")
Keyword.create(item: "Anti-fungal cream", name: "Grocery")
Keyword.create(item: "Band-aids", name: "Grocery")
Keyword.create(item: "Bar soap", name: "Grocery")
Keyword.create(item: "Body wash", name: "Grocery")
Keyword.create(item: "Cold medicine", name: "Grocery")
Keyword.create(item: "Conditioner", name: "Grocery")
Keyword.create(item: "Cosmetics", name: "Grocery")
Keyword.create(item: "Cotton balls", name: "Grocery")
Keyword.create(item: "Cotton swabs", name: "Grocery")
Keyword.create(item: "Deodorant", name: "Grocery")
Keyword.create(item: "Family planning", name: "Grocery")
Keyword.create(item: "Feminine products", name: "Grocery")
Keyword.create(item: "Floss", name: "Grocery")
Keyword.create(item: "Flu medicine", name: "Grocery")
Keyword.create(item: "Hair color", name: "Grocery")
Keyword.create(item: "Hair gel", name: "Grocery")
Keyword.create(item: "Hair spray", name: "Grocery")
Keyword.create(item: "Hand soap", name: "Grocery")
Keyword.create(item: "Hot/Cold rub", name: "Grocery")
Keyword.create(item: "lip balm", name: "Grocery")
Keyword.create(item: "Mosquito repellant", name: "Grocery")
Keyword.create(item: "Mousse Mouthwash", name: "Grocery")
Keyword.create(item: "Pain reliever", name: "Grocery")
Keyword.create(item: "Pepto Bismal", name: "Grocery")
Keyword.create(item: "Prescription", name: "Grocery")
Keyword.create(item: "Razors", name: "Grocery")
Keyword.create(item: "Shampoo", name: "Grocery")
Keyword.create(item: "Shaving cream", name: "Grocery")
Keyword.create(item: "Sun block", name: "Grocery")
Keyword.create(item: "Sun tan lotion", name: "Grocery")
Keyword.create(item: "Tissue paper", name: "Grocery")
Keyword.create(item: "Toilet paper", name: "Grocery")
Keyword.create(item: "First-aid kit", name: "Grocery")
Keyword.create(item: "Travel pack", name: "Grocery")
Keyword.create(item: "Tooth Brush", name: "Grocery")
Keyword.create(item: "Tooth Paste", name: "Grocery")
Keyword.create(item: "Toothpaste", name: "Grocery")
Keyword.create(item: "Vitamins", name: "Grocery")
Keyword.create(item: "Apples", name: "Grocery")
Keyword.create(item: "Doritos", name: "Grocery")
Keyword.create(item: "Cheetos", name: "Grocery")
Keyword.create(item: "Red Bull", name: "Grocery")
