User.create(username: "test", password_digest: "test", facebook_id: 1)
List.create(name: "Grocery List", user_id: 1)
Item.create(name: "Video Games", list_id: 1, keyword: nil)
Item.create(name: "Cheese", list_id: 1, keyword: nil)
Item.create(name: "Cereal", list_id: 1, keyword: nil)
Item.create(name: "Chips", list_id: 1, keyword: nil)
Item.create(name: "Cookies", list_id: 1, keyword: nil)
Item.create(name: "Apples", list_id: 1, keyword: nil)
# Item.create(name: "Video Games", list_id: 1, keyword: nil)
# Item.create(name: "halo", list_id: 1, keyword: nil)
# Item.create(name: "kleenex", list_id: 1, keyword: nil)
# Item.create(name: "world of warcraft", list_id: 1, keyword: nil)
# Item.create(name: "tomato", list_id: 1, keyword: nil)

# Item.create(name: "Halo Wars", list_id: 1, keyword: nil)
# Item.create(name: "battlefield", list_id: 1, keyword: nil)
